### ISSUE TITLE
Update to ITK5

### ISSUE THREAD

**Issue by dzenanz** [scifio/scifio-imageio#39]
We have entered development cycle for [ITKv5](https://discourse.itk.org/t/gearing-up-for-itk5/515). @hjmjohnson is leading the charge, but he needs write permissions for this repo to make his life easier while transitioning the remote modules. Can write permission be granted, or ownership of this repository [transferred](https://help.github.com/articles/about-repository-transfers/) to [InsightSoftwareConsortium](https://github.com/InsightSoftwareConsortium) organization?

**Comment by ctrueden** [comment]
I created a new team with admin rights to scifio-imageio and scifio-itk-bridge. The team initially consists of myself, @thewtex, @fbudin69500, @hjmjohnson (invited), and @blowekamp (invited).

Happy to expand the team further as needed; just let me know.

And maybe the ITK5-ization would be a good opportunity to finally convert this code to actually use SCIFIO instead of plain old Bio-Formats. :-)

**Comment by thewtex** [comment]
Thanks, @ctrueden !

**Comment by fbudin69500** [comment]
Thanks!

**Comment by dzenanz** [comment]
I feel left out of the new team :cry:

**Comment by ctrueden** [comment]
@dzenanz Cry no more—welcome to the club! 🔑
